### ISSUE TITLE
Form not submitting to Formspree

### ISSUE THREAD

**Issue by ryan0233** [ryan0233/confectionery-website#2]
@melissaroy

My form isn't submitting and I'm not sure why. I didn't use my school e-mail.

**Comment by melissaroy** [comment]
It wont work if you are looking at your local version (opening the index.html on your browser). You can only submit on the live version. I've opened it and tested it and worked fine. @ryan0233

**Comment by ryan0233** [comment]
Are you sure? Because Markbot isn't accepting it.
@melissaroy

**Comment by ryan0233** [comment]
You were right, I tested it on the live version and it worked, but Markbot still won't accept it.
@melissaroy

**Comment by melissaroy** [comment]
Your method="post" should be: method="POST"  Also I would add it before the email. That should fix your issue @ryan0233

**Comment by ryan0233** [comment]
THANK YOU!
@melissaroy
